[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
  TERM = "xterm"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
  from = "https://terrypi.com/my-notes/*"
  to = "https://publish.obsidian.md/serve?url=terrypi.com/my-notes/:splat"
  status = 200
  force = true
